### ISSUE TITLE
IntelliJ (2019.2.4) Plugin (0.6) throws Exception on project start

### ISSUE THREAD

**Issue by StefanLobbenmeier** [amelentev/java-oo#62]
This is the stacktrace:
```
com.intellij.ide.plugins.MainRunner$StartupAbortedException: Fatal error initializing plugin javaoo.idea
	at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:122)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.handleInitComponentError(PlatformComponentManagerImpl.java:33)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:520)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:126)
	at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:262)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.initProject(ProjectManagerImpl.java:285)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.convertAndLoadProject(ProjectManagerImpl.java:600)
	at com.intellij.platform.PlatformProjectOpenProcessor.tryLoadProject(PlatformProjectOpenProcessor.java:280)
	at com.intellij.platform.PlatformProjectOpenProcessor.prepareAndOpenProject(PlatformProjectOpenProcessor.java:254)
	at com.intellij.platform.PlatformProjectOpenProcessor.lambda$doOpenProject$0(PlatformProjectOpenProcessor.java:198)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:253)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:894)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$9(ApplicationImpl.java:552)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.intellij.diagnostic.PluginException: Can't find [myConstructor, a] fields in com.intellij.psi.impl.source.tree.JavaElementType$JavaCompositeElementType class [Plugin: javaoo.idea]
	... 25 more
Caused by: java.lang.NoSuchFieldException: Can't find [myConstructor, a] fields in com.intellij.psi.impl.source.tree.JavaElementType$JavaCompositeElementType class
	at javaoo.idea.Util.findField(Util.java:52)
	at javaoo.idea.Util.set(Util.java:67)
	at javaoo.idea.Util.setJavaElementConstructor(Util.java:85)
	at javaoo.idea.OOComponent.initComponent(OOComponent.java:53)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:503)
	... 22 more
```

**Comment by StefanLobbenmeier** [comment]
IntelliJ Version is 2019.2.4 Community Edition

Reproduction steps:
only install the plugin, don't configure anything, restart IntelliJ

**Comment by amelentev** [comment]
fixed. @StefanLobbenmeier please try to install new plugin version from
https://amelentev.github.io/mvnrepo/java-oo/idea-oo-plugin/idea-oo-plugin-0.7.jar

**Comment by StefanLobbenmeier** [comment]
Thanks the exception is gone now
